/**
 * report.js - Builds and downloads a markdown report of an investigation.
 * Kept dependency-free; uses only existing format/address helpers.
 */

import { formatTokenAmount, formatDate } from './format';
import { shortenAddress } from './address';
import { keccak256, toHex } from 'viem';

/**
 * Compute the keccak256 hash of the report markdown. This is the exact value
 * anchored on-chain by InvestigationRegistry, so anyone with the downloaded
 * report can recompute the hash and verify it against the registry.
 * @param {Object} investigation - The investigation result.
 * @returns {string} 0x + 64 hex chars.
 */
export function getReportHash(investigation) {
  return keccak256(toHex(buildReportMarkdown(investigation)));
}

/**
 * Build a markdown report string from an investigation object.
 * @param {Object} investigation - The investigation result.
 * @returns {string} Markdown report.
 */
export function buildReportMarkdown(investigation) {
  const {
    wallet,
    network,
    overview,
    tokens,
    transactions,
    counterparties,
    activityScore,
    attentionSignals,
    fetchedAt,
  } = investigation || {};

  const lines = [];
  const h = (t) => lines.push(`## ${t}`);
  const p = (t) => lines.push(t);

  lines.push(`# AI Wallet Investigation Report`);
  lines.push('');
  lines.push(`- **Wallet:** \`${wallet || 'Unknown'}\``);
  lines.push(`- **Network:** ${network || 'Unknown'}`);
  lines.push(`- **Generated:** ${fetchedAt ? formatDate(fetchedAt) : 'Unknown'}`);
  lines.push('');

  // Overview
  h('Wallet Overview');
  p(`- Balance: ${formatTokenAmount(overview?.balance)} BOT`);
  p(`- Transactions: ${overview?.transactionCount ?? 0}`);
  p(`- Token Transfers: ${overview?.tokenTransferCount ?? 0}`);
  p(`- Tokens Held: ${overview?.tokenCount ?? 0}`);
  p(`- First Activity: ${overview?.firstActivity ? formatDate(Number(overview.firstActivity) * 1000) : 'Unknown'}`);
  p(`- Last Activity: ${overview?.lastActivity ? formatDate(Number(overview.lastActivity) * 1000) : 'Unknown'}`);
  p(`- Wallet Age: ${overview?.walletAgeDays == null ? 'Unknown' : overview.walletAgeDays === 0 ? 'Less than a day' : `${overview.walletAgeDays} days`}`);
  lines.push('');

  // Activity score
  if (activityScore) {
    h('Activity Score');
    p(`- **${activityScore.total ?? 0}** / 100`);
    const parts = [];
    if (activityScore.frequency != null) parts.push(`Frequency: ${activityScore.frequency}`);
    if (activityScore.consistency != null) parts.push(`Consistency: ${activityScore.consistency}`);
    if (activityScore.diversity != null) parts.push(`Diversity: ${activityScore.diversity}`);
    if (parts.length) p(`- ${parts.join(' · ')}`);
    lines.push('');
  }

  // Attention signals
  if (attentionSignals?.length) {
    h('Attention Signals');
    for (const s of attentionSignals) {
      p(`- **[${s.severity}]** ${s.type.replace(/_/g, ' ')}: ${s.reason}`);
    }
    lines.push('');
  }

  // Tokens
  if (tokens?.length) {
    h('Token Holdings');
    lines.push('| Symbol | Name | Balance |');
    lines.push('| --- | --- | --- |');
    for (const t of tokens) {
      lines.push(`| ${t.symbol} | ${t.name} | ${formatTokenAmount(t.balance, t.decimals)} |`);
    }
    lines.push('');
  }

  // Counterparties
  if (counterparties?.length) {
    h('Top Counterparties');
    lines.push('| Address | Interactions |');
    lines.push('| --- | --- |');
    for (const c of counterparties) {
      lines.push(`| \`${shortenAddress(c.address)}\` | ${c.interactions ?? c.count ?? 0} |`);
    }
    lines.push('');
  }

  // Transactions
  if (transactions?.length) {
    h('Transactions');
    lines.push('| Direction | Type | Amount | From | To | Date |');
    lines.push('| --- | --- | --- | --- | --- | --- |');
    for (const tx of transactions.slice(0, 100)) {
      const amount = tx.isTokenTransfer
        ? `${formatTokenAmount(tx.value, Number(tx.tokenDecimals))} ${tx.tokenSymbol || ''}`
        : `${formatTokenAmount(tx.value)} BOT`;
      lines.push(
        `| ${tx.direction === 'incoming' ? 'IN' : 'OUT'} | ${(tx.type || '').replace(/_/g, ' ')} | ` +
        `${amount} | \`${shortenAddress(tx.from)}\` | \`${shortenAddress(tx.to)}\` | ` +
        `${tx.timestamp ? formatDate(Number(tx.timestamp) * 1000) : 'Unknown'} |`
      );
    }
    lines.push('');

    if (transactions.length > 100) {
      p(`_Showing 100 of ${transactions.length} transactions._`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('_Generated by AI Wallet Investigator on BOT Chain._');
  return lines.join('\n');
}

/**
 * Trigger a browser download of the investigation report as markdown.
 * @param {Object} investigation - The investigation result.
 */
export function downloadReport(investigation) {
  const md = buildReportMarkdown(investigation);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `investigation-${(investigation?.wallet || 'wallet').slice(0, 10)}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}